language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
  - secure: jPCY2WtIrp7qlbVk5SPp4xJbg8ZbuD6AlSeFx23aU9jUoqgh6Bxabg3zKiI6Q57VL9f35jxztuWvaX9NuLPbw4yCi9C1JRBrxd46BuTauH6Yv5LlUSk85BfGDM67DSMb+NuXa7efww8XRMf1OcbaBjHTgJkyBVwnpynbEVUknT3mfzVPzs3bFjvRIUTxmAFkPPY7oLszCdKeZY0Axd2ycOs8cF5+xN4uISX3/R8gd7l6O+EayEQJTm0gMnnN5vkCVsmRGvV+u/ncmnZqFQ5kOAfZboNOahJll7aFBW2fUuZKITHrnqkb3iSjT5ePFF3e4nWzpfuMZRS32IJkvdJ99EcuYRWs98vDQcXsyojr7ktQU7yT9VsfbXKsqa8oRS4K1FdkYWGIcKQZqDjY74frnFhwfmKIQ9kWVxKZ+zScyFxq6YN1Cw3q5uYddBrj3TCt615ts3vn6XmAD9pdg+FFFaBIDS50lpmdY2bLRud1ALI5sHz561Iqtuevciu1T6ujZMvsnLUrmEpq7it2D7n7ApKPcnaoSldgiMFW04UmAKKlvZLFxqWG0AsCYL43Bq0CfKtJWYB/qejeiDKbPHg6G7tqlKvXz1wVM+zcztNleF6LwKu4Wr/l638d4Aa3wOixYNsuGfGOp0yfwxolB43rCBE2QjOblqRRsUQYPQmmjco=
  - secure: itUWPAJagC+mmcnbKibJ13dresspoZyXUg6yOcoe1ZFDbXFpalgyHdo43RQJgmNjX9wxVI1taqyANmNAp9mCMpkpFN9OUZfyPo4QU8DNJLaYU4LfGb2Z6TJVeHLVNu/b2phgJc2vujCHyiO+B9/ROLSPUdvBVcyLsaoo+4pWaWiI5mur0uAZHcHjbOVkf3b2jBxu9RnGkPQZMO6DoePy4N+RI1B/tFo2+jtF+vbs/Y+0U+Luj43csoeSvonvyX33b18pj767h4hMMBj+lqckgmFYNvyo7XeBlqLGzRxXISNOzj15MxFa8bIY6//ovVP8RGhYNbf8RES2sp41uLK2Xm7CCLMFWynAbz4LpE7k+30jP6wdoTkJcDpeHvSM0TFlB3IZW/m3PZffr+5xJtfsT/LBKYNbzfjr0rfKag9HghStl49J7LIN6+zFDdAakXB/JnHOOvEmAOH8DLUIT3nNPSe0Dkf7SQP5nPuUbswINlWRHCrnGEpF+2l8Qe2VKXpOcm1rMDgTOkWdx9s0Rsh5bz2LzGwPFy7BUd6Kj8eDA1w2d0rWPRbYnPd9JIbECXcg+HXeNUTemML9UBGzYnGQc+rR2miSH0O/znl54ThOMZZemyXSs3mg+BvQ4xeuKZqVPILwE9NaqVXuMpW3Rxm6gcxcjj0vgOdPFPRbtvRm+jY=
  - secure: bYC433mSYqbVbMjlEtTs8/syhdwBfJ83ZxImL+hut8GHdxIskQBoA/fU6GzJKz7H6cHCnuSxNFo2OrnOL3HTqAOq9ZHCqQLzpCoBjpz/bw/Ps9WfmWMs73Xm77a19YCTvZKUzSr/jx1gMJODSaHWr0inqrxLGkyFwAVFnuyVNC5zqgfZPOFsoGhaZw+Ucj0sOb2igjfEczRZNjioW2h+OsO5gzuZ6gaRX+4ZwvXHnqgfqshJy9spaRpvmJ9ESF5C3oktdDRj1wtvCMRJmhEjVJ4Uf00fGmMLGq3SKy8+f4XwA2mGTLPbIe/xsstT/28jv0620khJ7a/F1r052Wv7oyHTuNO1yRIsgTmzXJwldXlvfRERM2ihQRDDFA5Wv6TfYhmzY7HtHvuU9w4HC8SjSeinnWgA4kfJZNfbNH/lRrfj4+BLS4XVVlesVHLjVsDcNnuDWLhapwf28p9ZKhadQeA1zzGO1u4QIOSFZ+WLMtVeqdLaVTLgVij9I914OmTzPMw3v+j8LezVPeTNfGalF4Ao56fDwLY2Xkhk3vqREyWklKSrPTFOX/mAi+V+lkUMdrv1k6RWgsWmDvbjp6Z5n67945hycDdF+w3w35f+jZBEiKFn+qSYL/p6diIeez3l6Fga/yZebHqxRZlAoeexsrpMtHATpfeSaH6RD5PtgIo=
