language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
  - secure: rwrMdY/ig9Wva7hmDh9KYxqM6aFPwsrkvbeUCI90k/v5QJciMlOSPaGbaqvS4rt7gfpstewOzXOdy6ghW/CUIVZbN7Lnl3dVbcHBPb9OgAP3RM8CZ23Yklsu/zDvoHfnMOqXZyma2M+CqcWS7eJjN/T7BHP7Lx8ctzTsc0FODxVHAOOJdLwC3i6IqPJgpXbdNWznj7YxKAg93veow/uGWkqdi3lCn6bRWZIMJvS3amRkAuUgZ6xPXRYB0Sj4cxOa3oGWZloU2qv3dcmKuuDKec59bK2Yao02Tfac1JpCaPpybiPBx7sm0sIt5xxB1yjJ6AkHq4b6ljWqJtNpvKWIrxEqxlxQljZW9Mr1HCoprOlVxDExBrZxfVUn8v6y5cY5F0wU01Rl0gGt9/57lhV4vGH9LoJqxEXarNK1MVMtW75TXCGAeVit5n6zlVeLycgDDmRQCLNfpDRccwwckTvxfdb565BRbgXM4MjzDIdeBvf2jQkmGj0PiNcFRgpVjyWL3G+r+eUWgmDR4/lq5SVxeuBuh4l3/VLVJqVeVE72D5tTuDxPT2BzBykohtoveWIoQeq7akLgNaCn+dA9V6MkLkLoVkTWoUzkPv9y+UA51+5mpLJjyP5oGncSARF5LXH8gH+yWnwSsMYzEufeYtmo9zKPtv7DCV6hTm1gDkldKog=
  - secure: HsyCphzMLK5IsBP+8T2LuyVJCMlUfcDSuQW9PRxlM14cV2YuRiMLdsqJ+HHC7RacIEwQBJOecUOlRJsV4IxYU4HkJO/G9XkD7Sx3xObhAYKKJd5NtwS8gxtD6HHpsUrYyoPnd/cDJDvwnrjJmsRVjjxrLa7G77q0kE0agqat0lpxmX59B6IksJHTNbGuUwQ2oUyHsdEdl9cS+5xxjC5VmW5AiFSCTlFAkfcOi5QWpz7Nj6JBDxpB5YBvu/say+NeA7wpgD7ybEXk4Xs9lF/KVKvoscrSvo5x1A1iBIo4WpEil2Wm/aNXScYfaWsKjXht8LBh27ueaOjMYf4U5dpKS5es4HyFlLAyHx+m1DCJFJxebJvHE8k8x/ocas9UO+NVmZVsQrKELmKa5hlVr+gxNlLErKqadyYJfbyhdEBgMswIep4hAUXYiUduQsZ25ZjBPXPYZScwwCM1KNW9bJ2oQInjkcpmjynmuZnQuq1EDFlSlHSa8JulIRZRK5u2mUJFp3hxenzzzdpcL+hLWhTB6xL7KiYvACR9CdYSQj/Sutce2bpF+fYJh8yurv1z4QU0q1RiII1ur1JotJd6Rsw/gEz5i3/Choo7fOQSGGA6uQA8HD85wOhCk8Notx98nO2XbO5cFgmm6BPpQV34OUv8poJ6B95B2YtwPjAppGiQlTg=
  - secure: Zp0uVSfkuA8cuq9SQHqPHorhjruT8uxDTrgHGxXKlENpfV2nJGO193KQtWfvYN/KE/a7H5lIac+KAUN+kounr07Gv5LUpXL6bW+HG34aptKn5VxgrevRIeukU5gHFAIh7jrD1qLpNhuwa4RrAzNFv4JJuLGonzYg24r2iO4KWVpPlIIN6a5JfypDutcIr4C62uXrz4+9q4jMyQp7cWO6GgJ9IO7y6rxYQ8ts6SdxVQUCweDmoh2NAJhUFgAB88sM2FgBO9U+wRU/eGY7mDPhnLOCwLO+Gpyv7odZwy5G4KRzyj+8gvkzZ9p5JUp2fSu0C15mQb0o5l6p00rRTPuvBLEi2hBvwGw+90wiF0EBZDAxwNwWdNd5UPHrNggWLy4k5LNM6EAx/UGF65PAUbzz/r4GB5W2v5wwtvWIoo7O+xc9QhrJy6f1gB3ycD+6Rd17wdijZxq5qVPm4f+KYfEYSOY5rznqy6y/CnZGZFc2vjrmdggMSqMUcqYYzcrCDLMACFuSJTeSVZtCa8+f0JumwmRNu+ZwzEDT78vUlmaOCeTeeSnZW9u9gTpuok54hm+KnJCalpiaNbhuYaspn1u3nZ6k+5vXcNe1gpWgb9qjx132aLmIJw1BGNTqcCIutdmkTVac+VkmaJFNfgUv0buMzL+wmtVx+EVG3TTdrn1XU6A=
