language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
  - secure: jNpclnEdtYioCamaKWWFAsD4weWyBlAiixBclKHVYcxfp9snwtef6RaMlmiGyv3FBJl2Z9yC11OJi9sMjDkzz1F1MirZgpX6tzZmaqErRCz/Ax782lKUDLznyx0h+XNaLHi0azlEKp4c2k5PuaaFCWDp8vkVYueN2gUeOOU5jWkq10Sn1vLFcEDL8Y7ryOFvgyfxrl6t5m14vOhp5S3HF0sqt2qgXXf3rgdBtXB44V4s+eWBULLv3y4o0fkVtd+aUaiUd3FfGzFY//CDcSsdiFUeGweNBc8ci7f22qtm0yIWE/0GvOt5K8d1nWp9q4E0jmabZQvImO3hh3OhPSkvVwfVcg/D4wUQmeEPOAOPZvcfwhTj6g52Zofy3w7HU+OXjfxEq0M27CNtq3bkK4EOAH1C3H8MynEugGEgIiSlFazsYbOeObV/578QSoL0U+il1QOl/Qxj/3NO1DZPthz1Cg2UH16BHFrHLm0FoS7TnMY+qXJ17QXZ+gbH7mNE/6QmnsuNH5mkOPbIUOB9ElZU/eUWEYdYW3ryd4Xip6OSSvV36C4pdmaeEks/D44+2SzW5EIJJeq24sw/thmYTJ/PQP+Qk8msk15tbaPA5UM17bPTk1u6CWduyAIpwaJ71Qq+Ai3LGOr9LdY8hShkI7V7mMf7KJDwUKYpuuo/eU0u5uA=
  - secure: mVfDDTjac5sv9nbWwSzCS1Jw5GfRPk5dZOoig6vcRFVhYU27uoPbwg7gtRXD6LmM9nLBlwvsN+oj4q0JOhNxguLmyzZn+d44d+9kcSWmLKO/LS+Z1qrczmAzL8nnV59vnhd5+WmjFOQx75sW7k2m4bDgmS6XARTcatTvj6ZGrxd4kWcoQOpy94y4jfhBv3hBjCsNAbHLeRkx8Vn0obhrHh/n5yRS1+w5plvhuROFTiWCZzDNbgtH/38+mV4U2jpVdigACOlXUzrdRAYnzaTDlOa36MYQu8DT2WG61jA66gSQ76AdhUZjZdUsAkegVgJAaG5V1VIE9PKacLzk9j+2uAe6HwysCkx0gqs0TGTK0YwR8LD3owSR1Msr6QMO1J1328/eVKxd85KomD7Ni59MO9W5ZkZ++JNZl+Hfw6aAp3PLBcMSZOnGwvgZJFdIC4zuBQqSzeBCIqBc37f26CT9PyUPKqL5VkP+LJ4HnADumjipg5XapoveRwpIItVRuKo6lYwE3k14KWMHtU2RWuB31BA+IJH1PxEZOQk+rL+L0QAb+U/RNJZrOXcri+tQNQAh8oB3VD26UULMB/z3A6bBS+M11045V8CvAD33PpWcq95LDoSdbX6a9fu0kWgnPNSPgz0L5MoKRFiTZZYNnRNGY4YRUfyTOaH5ejiuI25htzw=
  - secure: SviY5R4I5AbMiD0wG0lNGATlFxP1sjiYH0I875LyOjLi7OBlCAf75UckP8tZEgI4V+HN0Vn6OrLz2i04LftcZwy8NUc71I/HM9CMD62qU4DbG1uyeLMcqMo/1+hDJlu2ZAAOXJ5j/6DTp8FMg9DCr3JK9PgpnkvcvRW5TBvdw/6Ym6MzHMQ6uPv336laPsMhJZqMbjKSCQ8QOxot9qusD8Crp5DyEPqlO4CH3GTS+mu4c2c2xPug9CHsAWJllBTiOkrAY0RIPAok9jzlU1IWwtS6GyMqP/73gWd7VW2JhlGv3tbNQXlgeiwnZy9aNXVGL+VpJOGwbYQ1bLhpIeOIo5FWdB218kQKGZ5P5hsoWuMTD3k4BooPgsl9pEEtZYSldSyZC7I08K22UxgtAeNOXGN7VcW73Z7J0dz6GFDqdSS4MBP0aSO08EIj42Z/uHUqyNArqGDBP2jgClvPpCXKRK+Ka3HYlZMx1zB7XwqPxuFYNqARIBolq7zzXEiAYBsTpS50bZWCzwPVBSAIdT4qcjO0NTuYOHFYFpRH/E0TYUQbMDBUdu850wRcF1emeNHQzWKERhRlgeKKYMLm5b3JyZAMFOi9mDB/9hGtf4ZBj3fC9QIoqT+YR+qIDZGfNeIVjTLQkglMz0CHs2qxRszj0+XvqnSgYKQiQDouSIRcKi4=
