language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
    secure: eKv6QNjgZJuHoJZH1N4oiACMfZXp0kTSHYPVJk8RfdGyzriVVn2X5GoAW7HTYJ2aOoUgPZtJ2TC9t8DXdRDWzCiYN92jAvnHzYB3ZXQpmCq16pTPjLuiwRAaLJvVsgJg8R65QoPZEzBzP7Okt76bG3vm2FL2CP1XV9roMylw6fTMTpKGRpgoJPhuQxvjsfaYtFt2Ik6VkedvgHqS9tfE4kJytQbZVazX05yFvvS+4Eg++sZiD0rE8V6nTHrajH6YM+DmKXqzOE7We2KRxGJrSFqBapPGZ15UuQkzt5fFESTnnERRx8LO7e/2S/+khaQadTTFofeYBcQ6p8Ut8KD+3Zj+Z31FBJD6i9MHzWIt4w01HQZYaBwBo+AraBILjLxDFi32un6DNqln6xUtDrA3LqzhvQ065pWnJA4Z0D3vw0/AlcwL1eYyH2O1p9VY/15U6HK8ftkyb/5sdfcFwkEdGqOPrg09JS6oAvCWIrP7mldasNd89Esk1/MaPbKXFCjrAfE1buvtz1fOnOb6Q3CqzWqbGEbuitPx8EXC6fM2DIDKV6okjMEumlAAMweaIxXLMUJT/7KF9N/e/8nFuSMC/EmmlaoUUQcog8TZO7DReliUXlKUpxMK2p9TyWgUWNMHGsq/zHKnWG4nSq9DclgD3UQKIYFmLwQhSmMMGiULyZI=
