language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: echo 'Running unit tests'
script: npm test
before_deploy: echo 'All unit tests passed; Preparing to deploy to AWS'
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-production
  on:
    branch: master
after_deploy: echo 'Successfully deployed to AWS'
env:
  global:
    secure: Zc/JfF0KNrD2vGNsfMd8cFeU+qhrsnz5MEzkFS5ouXkgkG65tV6sZpvRiu/l4NSksSuvaknqWmacaTCuWIS6vgwgzPrnRuW02Lpp/C2QYaXglwGkYiwpWIW9Ro1eP3+sDRMX68dkQUpwTw/Qd/KPthF98DlCkMqskHUNGOMkEinPWs8PjQHIfZanHbiE52lj7r6fQsq9JAOo9cj71XIP+uEBenA/9zwu19yQs6b+YDb+UzDuY8xHQEpl+oRVBeXt7FN3v3iMbNPGU8vKWKcvYQjG86u78JOkiWU1SD7RgVUon0VSfSc62Gfxq7eR5j0oewmtXpHzbGhpqy27uIn088iVz2SvGmE8NnyEt77uR9MCd7U2IyYnHl05pvGLFeRVUu53W99HlDorBXWcVCd4PjwhnpKQ3fcoqjqJwqoytd2C1m23nffpmMSiToSuF0Cu6SS2dETMPeiegBqbD5AmDPReENEUNDZHsR80RL96ixyGlySzbpaPOusbSBt1Rimn5SCw4d+h6ozEum95l0xBj18PQskeME9Z/wmWX6lJn0GlH/bNLANxDxSkS4NYXV8j/5RPnQDMWJgbp7IvR2/ZFtWUngHE3+p2G5gQ4gn+GPnZr45nvMbJ5AWdIE1Q2SSI8svBq0T5Hxcm8LkBzIRZnfJGiUqF4fPhqBeFKW/q6/E=
